@extends('frontend.layouts.app')

@section('content')
@php
    $catalogSection = $sections->first(fn ($section) => in_array($section->section_type, ['catalog_categories', 'catalog_items', 'featured_catalog'], true) || in_array($section->section_key, ['catalog', 'categories', 'items'], true));
@endphp
<section class="bg-gradient-to-b {{ $pageFallback['gradient'] }} to-white py-16 dark:to-slate-950"><div class="mx-auto grid max-w-7xl items-center gap-10 px-4 sm:px-6 lg:grid-cols-2 lg:px-8"><div><span class="text-sm font-extrabold uppercase tracking-[0.18em] text-red-700 dark:text-amber-300">{{ $pageFallback['eyebrow'] }}</span><h1 class="mt-4 text-4xl font-extrabold tracking-tight text-slate-950 sm:text-5xl dark:text-white">{{ $page?->h1 ?: $pageFallback['h1'] }}</h1><p class="mt-5 text-lg leading-8 text-slate-600 dark:text-slate-300">{{ $page?->intro_text ?: $pageFallback['intro'] }}</p><div class="mt-8 flex flex-wrap gap-3"><a class="inline-flex items-center justify-center gap-2 rounded-xl bg-red-700 px-5 py-3 text-sm font-extrabold text-white shadow-sm transition hover:bg-red-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-600 focus-visible:ring-offset-2 dark:bg-amber-400 dark:text-slate-950 dark:hover:bg-amber-300" href="{{ $pageFallback['button_url'] }}" target="_blank" rel="noopener">{{ $pageFallback['button_label'] }} <svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="M5 12h14M13 6l6 6-6 6"/></svg></a><a class="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-300 bg-white px-5 py-3 text-sm font-extrabold text-slate-900 shadow-sm transition hover:border-red-300 hover:text-red-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-600 dark:border-slate-700 dark:bg-slate-900 dark:text-white dark:hover:border-amber-400 dark:hover:text-amber-300" href="{{ $pageFallback['secondary_url'] }}">{{ $pageFallback['secondary_label'] }}</a></div></div><img src="{{ $pageFallback['image'] }}" alt="{{ $pageFallback['image_alt'] }}" width="720" height="480" class="w-full rounded-[2rem] border {{ $pageFallback['border'] }} shadow-xl dark:border-slate-800" decoding="async"></div></section>
<section class="py-20"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div class="max-w-3xl "><span class="text-sm font-extrabold uppercase tracking-[0.18em] text-red-700 dark:text-amber-300">{{ $catalogSection?->subtitle ?: $pageFallback['sections'][0]['eyebrow'] }}</span><span role="heading" aria-level="2" class="mt-3 block text-3xl font-extrabold tracking-tight text-slate-950 sm:text-4xl dark:text-white">{{ $catalogSection?->title ?: $pageFallback['sections'][0]['title'] }}</span><p class="mt-4 text-base leading-8 text-slate-600 dark:text-slate-300">{{ $catalogSection?->content ?: $pageFallback['sections'][0]['description'] }}</p></div>
@if($catalog['hasCategories'])<div class="mt-10 grid gap-5 md:grid-cols-3">@foreach($catalog['categories'] as $category)@include('frontend.catalog.category-card', ['category' => $category])@endforeach</div>@else<div class="mt-10 grid gap-5 md:grid-cols-3">@foreach($pageFallback['cards'] as $card)<div class="rounded-3xl border border-slate-200 p-6 dark:border-slate-800"><span class="text-red-700 dark:text-amber-300">@include('frontend.partials.home-icon', ['icon' => $card['icon'], 'class' => 'h-6 w-6'])</span><span role="heading" aria-level="3" class="mt-4 block text-xl font-extrabold">{{ $card['title'] }}</span><p class="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">{{ $card['description'] }}</p></div>@endforeach</div>@endif</div></section>
@if($catalog['hasFeaturedItems'])
<section class="border-y border-slate-200 bg-slate-50 py-16 dark:border-slate-800 dark:bg-slate-900/50"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><span class="text-sm font-extrabold uppercase tracking-[0.18em] text-red-700 dark:text-amber-300">Featured convenience items</span><span role="heading" aria-level="2" class="mt-3 block text-3xl font-extrabold tracking-tight text-slate-950 sm:text-4xl dark:text-white">Admin-managed featured products.</span><div class="mt-10 grid gap-6 md:grid-cols-3">@foreach($catalog['featuredItems'] as $item)@include('frontend.catalog.item-card', ['item' => $item])@endforeach</div></div></section>
@endif
@if($catalog['regularItems']->isNotEmpty())
<section class="py-16"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><span class="text-sm font-extrabold uppercase tracking-[0.18em] text-red-700 dark:text-amber-300">Current catalog</span><span role="heading" aria-level="2" class="mt-3 block text-3xl font-extrabold tracking-tight text-slate-950 sm:text-4xl dark:text-white">Active convenience-store items.</span><div class="mt-10 grid gap-6 md:grid-cols-3">@foreach($catalog['regularItems'] as $item)@include('frontend.catalog.item-card', ['item' => $item])@endforeach</div></div></section>
@endif
<section class="border-y border-slate-200 bg-slate-50 py-16 dark:border-slate-800 dark:bg-slate-900/50"><div class="mx-auto grid max-w-7xl gap-10 px-4 sm:px-6 lg:grid-cols-2 lg:px-8"><div><div class="max-w-3xl "><span class="text-sm font-extrabold uppercase tracking-[0.18em] text-red-700 dark:text-amber-300">Location</span><span role="heading" aria-level="2" class="mt-3 block text-3xl font-extrabold tracking-tight text-slate-950 sm:text-4xl dark:text-white">Convenience store at 6168 Oxon Hill Rd.</span><p class="mt-4 text-base leading-8 text-slate-600 dark:text-slate-300">Use the verified address when navigating to the business. The store is in Oxon Hill, Maryland, ZIP code 20745.</p></div></div><div class="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200 dark:bg-slate-950 dark:ring-slate-800"><span class="block text-sm font-extrabold text-slate-950 dark:text-white">{{ $business['short_name'] }}</span><p class="mt-2 text-sm leading-7 text-slate-600 dark:text-slate-300">{{ $location['address'] }}, United States</p><a href="{{ $location['map_url'] }}" target="_blank" rel="noopener" class="mt-5 inline-flex items-center gap-2 text-sm font-extrabold text-red-700 dark:text-amber-300">Open in Google Maps <svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="M14 4h6v6M20 4l-9 9"/><path stroke-linecap="round" stroke-linejoin="round" d="M18 13v6a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h6"/></svg></a></div></div></section>
@endsection
