@extends('frontend.layouts.app')

@section('content')
@php($catalogSection = $sections->first(fn ($section) => in_array($section->section_type, ['smoothie_menu', 'catalog_items', 'featured_catalog'], true) || in_array($section->section_key, ['smoothie-menu', 'catalog', 'items'], true)))
<section class="bg-gradient-to-b {{ $pageFallback['gradient'] }} to-white py-16 dark:to-slate-950"><div class="mx-auto grid max-w-7xl items-center gap-10 px-4 sm:px-6 lg:grid-cols-2 lg:px-8"><div><span class="text-sm font-extrabold uppercase tracking-[0.18em] text-red-700 dark:text-amber-300">{{ $pageFallback['eyebrow'] }}</span><h1 class="mt-4 text-4xl font-extrabold tracking-tight text-slate-950 sm:text-5xl dark:text-white">{{ $page?->h1 ?: $pageFallback['h1'] }}</h1><p class="mt-5 text-lg leading-8 text-slate-600 dark:text-slate-300">{{ $page?->intro_text ?: $pageFallback['intro'] }}</p><div class="mt-8 flex flex-wrap gap-3"><a class="inline-flex items-center justify-center gap-2 rounded-xl bg-red-700 px-5 py-3 text-sm font-extrabold text-white shadow-sm transition hover:bg-red-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-600 focus-visible:ring-offset-2 dark:bg-amber-400 dark:text-slate-950 dark:hover:bg-amber-300" href="{{ $pageFallback['button_url'] }}" target="_blank" rel="noopener">{{ $pageFallback['button_label'] }} <svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="M5 12h14M13 6l6 6-6 6"/></svg></a><a class="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-300 bg-white px-5 py-3 text-sm font-extrabold text-slate-900 shadow-sm transition hover:border-red-300 hover:text-red-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-600 dark:border-slate-700 dark:bg-slate-900 dark:text-white dark:hover:border-amber-400 dark:hover:text-amber-300" href="{{ $pageFallback['secondary_url'] }}">{{ $pageFallback['secondary_label'] }}</a></div></div><img src="{{ $pageFallback['image'] }}" alt="{{ $pageFallback['image_alt'] }}" width="720" height="480" class="w-full rounded-[2rem] border {{ $pageFallback['border'] }} shadow-xl dark:border-slate-800" decoding="async"></div></section>
@if($catalog['hasItems'])
<section class="py-20"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div class="max-w-3xl "><span class="text-sm font-extrabold uppercase tracking-[0.18em] text-red-700 dark:text-amber-300">{{ $catalogSection?->subtitle ?: 'Current menu' }}</span><span role="heading" aria-level="2" class="mt-3 block text-3xl font-extrabold tracking-tight text-slate-950 sm:text-4xl dark:text-white">{{ $catalogSection?->title ?: 'Admin-managed smoothie menu.' }}</span><p class="mt-4 text-base leading-8 text-slate-600 dark:text-slate-300">{{ $catalogSection?->content ?: 'Smoothies, ingredients, options and prices below come from the catalog admin panel.' }}</p></div>@if($catalog['hasCategories'])<div class="mt-10 grid gap-5 md:grid-cols-3">@foreach($catalog['categories'] as $category)@include('frontend.catalog.category-card', ['category' => $category])@endforeach</div>@endif<div class="mt-10 grid gap-6 md:grid-cols-3">@foreach($catalog['items'] as $item)@include('frontend.catalog.item-card', ['item' => $item])@endforeach</div></div></section>
@else
<section class="py-20"><div class="mx-auto grid max-w-7xl items-start gap-12 px-4 sm:px-6 lg:grid-cols-2 lg:px-8"><div class="max-w-3xl "><span class="text-sm font-extrabold uppercase tracking-[0.18em] text-red-700 dark:text-amber-300">Current menu</span><span role="heading" aria-level="2" class="mt-3 block text-3xl font-extrabold tracking-tight text-slate-950 sm:text-4xl dark:text-white">Selection can change by day and inventory.</span><p class="mt-4 text-base leading-8 text-slate-600 dark:text-slate-300">Rather than publishing flavors or prices that have not been verified, this page sends customers to the physical store for the current smoothie menu.</p></div>
<div class="rounded-[2rem] border border-slate-200 bg-slate-50 p-7 dark:border-slate-800 dark:bg-slate-900/60"><span role="heading" aria-level="3" class="block text-2xl font-extrabold">What this page will support later</span><div class="mt-5 grid gap-4">@foreach(['A real smoothie menu with ingredients and prices once the owner confirms them.','Accurate availability and seasonal items without inventing products.','Food and beverage photos optimized as WebP/AVIF when the store provides originals.'] as $item)<p class="flex gap-3 text-sm leading-7 text-slate-600 dark:text-slate-300"><svg class="mt-1 h-5 w-5 shrink-0 text-red-700 dark:text-amber-300" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="m5 12 4 4L19 6"/></svg>{{ $item }}</p>@endforeach</div></div></div></section>
@endif
@endsection
