@extends('frontend.layouts.app')

@section('content')
@php($catalogSection = $sections->first(fn ($section) => in_array($section->section_type, ['adult_catalog', 'catalog_items', 'featured_catalog'], true) || in_array($section->section_key, ['adult-catalog', 'catalog', 'items'], true)))
<section class="bg-gradient-to-b from-slate-100 to-white py-16 dark:from-slate-900 dark:to-slate-950"><div class="mx-auto grid max-w-7xl items-center gap-10 px-4 sm:px-6 lg:grid-cols-2 lg:px-8"><div><div class="inline-flex rounded-full bg-red-700 px-3 py-1.5 text-xs font-extrabold uppercase tracking-[0.16em] text-white">{{ $pageFallback['eyebrow'] }}</div><h1 class="mt-5 text-4xl font-extrabold tracking-tight text-slate-950 sm:text-5xl dark:text-white">{{ $page?->h1 ?: $pageFallback['h1'] }}</h1><p class="mt-5 text-lg leading-8 text-slate-600 dark:text-slate-300">{{ $page?->intro_text ?: $pageFallback['intro'] }}</p><div class="mt-8 flex flex-wrap gap-3"><a class="inline-flex items-center justify-center gap-2 rounded-xl bg-red-700 px-5 py-3 text-sm font-extrabold text-white shadow-sm transition hover:bg-red-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-600 focus-visible:ring-offset-2 dark:bg-amber-400 dark:text-slate-950 dark:hover:bg-amber-300" href="{{ $pageFallback['button_url'] }}" target="_blank" rel="noopener">{{ $pageFallback['button_label'] }} <svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="M5 12h14M13 6l6 6-6 6"/></svg></a><a class="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-300 bg-white px-5 py-3 text-sm font-extrabold text-slate-900 shadow-sm transition hover:border-red-300 hover:text-red-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-600 dark:border-slate-700 dark:bg-slate-900 dark:text-white dark:hover:border-amber-400 dark:hover:text-amber-300" href="{{ $pageFallback['secondary_url'] }}" target="_blank" rel="noopener">{{ $pageFallback['secondary_label'] }} <svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="M14 4h6v6M20 4l-9 9"/><path stroke-linecap="round" stroke-linejoin="round" d="M18 13v6a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h6"/></svg></a></div></div><img src="{{ $pageFallback['image'] }}" alt="{{ $pageFallback['image_alt'] }}" width="720" height="480" class="w-full rounded-[2rem] border border-slate-200 shadow-xl dark:border-slate-800" decoding="async"></div></section>
@if($catalog['hasItems'])
<section class="py-20"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div class="max-w-3xl "><span class="text-sm font-extrabold uppercase tracking-[0.18em] text-red-700 dark:text-amber-300">{{ $catalogSection?->subtitle ?: 'Adult-only catalog' }}</span><span role="heading" aria-level="2" class="mt-3 block text-3xl font-extrabold tracking-tight text-slate-950 sm:text-4xl dark:text-white">{{ $catalogSection?->title ?: 'Admin-managed 21+ retail information.' }}</span><p class="mt-4 text-base leading-8 text-slate-600 dark:text-slate-300">{{ $catalogSection?->content ?: 'Active adult-retail categories and items below come from the catalog admin panel and remain informational.' }}</p></div>@if($catalog['hasCategories'])<div class="mt-10 grid gap-5 md:grid-cols-3">@foreach($catalog['categories'] as $category)@include('frontend.catalog.category-card', ['category' => $category])@endforeach</div>@endif<div class="mt-10 grid gap-6 md:grid-cols-3">@foreach($catalog['items'] as $item)@include('frontend.catalog.item-card', ['item' => $item])@endforeach</div></div></section>
@endif
<section class="py-20"><div class="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8"><div class="max-w-3xl "><span class="text-sm font-extrabold uppercase tracking-[0.18em] text-red-700 dark:text-amber-300">Age restriction</span><span role="heading" aria-level="2" class="mt-3 block text-3xl font-extrabold tracking-tight text-slate-950 sm:text-4xl dark:text-white">Federal tobacco sales rules apply.</span><p class="mt-4 text-base leading-8 text-slate-600 dark:text-slate-300">Federal law prohibits retailers from selling tobacco products, including e-cigarettes, to anyone under age 21. FDA rules also require photo-ID checks for customers under 30 who attempt to purchase tobacco products.</p></div>
<div class="mt-8 rounded-3xl border border-red-200 bg-red-50 p-6 dark:border-red-900 dark:bg-red-950/30"><span role="heading" aria-level="3" class="block text-xl font-extrabold text-red-900 dark:text-amber-200">{{ $catalog['ageRequirement'] ?: 21 }}+ only</span><p class="mt-3 text-sm leading-7 text-red-900/80 dark:text-red-100/80">Bring valid identification. Product availability and lawful sale eligibility are determined in store under applicable federal, state and local requirements.</p></div></div></section>
@endsection
