@php $detailsValue = old('details', is_array($item->details) ? json_encode($item->details, JSON_PRETTY_PRINT) : $item->details); @endphp
<div class="card-body">
  <h5>Basic Information</h5>
  <div class="row"><div class="col-md-4 mb-3"><label class="form-label">Category <span class="text-danger">*</span></label><select name="catalog_category_id" class="form-select">@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('catalog_category_id', $item->catalog_category_id) == $category->id)>{{ $category->name }} ({{ str_replace('_', ' ', $category->business_area) }})</option>@endforeach</select>@error('catalog_category_id')<div class="text-danger small">{{ $message }}</div>@enderror</div><div class="col-md-4 mb-3"><label class="form-label">Name <span class="text-danger">*</span></label><input name="name" value="{{ old('name', $item->name) }}" class="form-control @error('name') is-invalid @enderror" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-4 mb-3"><label class="form-label">Slug</label><input name="slug" value="{{ old('slug', $item->slug) }}" class="form-control @error('slug') is-invalid @enderror">@error('slug')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
  <div class="row"><div class="col-md-4 mb-3"><label class="form-label">Item Type</label><select name="item_type" class="form-select @error('item_type') is-invalid @enderror">@foreach($itemTypes as $type)<option value="{{ $type }}" @selected(old('item_type', $item->item_type) === $type)>{{ str_replace('_', ' ', ucfirst($type)) }}</option>@endforeach</select>@error('item_type')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-4 mb-3"><label class="form-label">Brand</label><input name="brand" value="{{ old('brand', $item->brand) }}" class="form-control"></div><div class="col-md-4 mb-3"><label class="form-label">SKU</label><input name="sku" value="{{ old('sku', $item->sku) }}" class="form-control"></div></div>
  <div class="mb-3"><label class="form-label">Short Description</label><textarea name="short_description" rows="2" class="form-control">{{ old('short_description', $item->short_description) }}</textarea></div>
  <div class="mb-3"><label class="form-label">Description</label><textarea name="description" rows="4" class="form-control">{{ old('description', $item->description) }}</textarea></div>
  <h5>Pricing</h5>
  <div class="row"><div class="col-md-3 mb-3"><label class="form-label">Price</label><input type="number" step="0.01" name="price" value="{{ old('price', $item->price) }}" class="form-control"></div><div class="col-md-3 mb-3"><label class="form-label">Compare At Price</label><input type="number" step="0.01" name="compare_at_price" value="{{ old('compare_at_price', $item->compare_at_price) }}" class="form-control"></div><div class="col-md-3 mb-3"><label class="form-label">Price Label</label><input name="price_label" value="{{ old('price_label', $item->price_label) }}" class="form-control"></div><div class="col-md-3 mb-3 d-flex align-items-end"><div class="form-check form-switch mb-2"><input type="hidden" name="is_price_visible" value="0"><input class="form-check-input" type="checkbox" name="is_price_visible" value="1" id="is_price_visible" {{ old('is_price_visible', $item->is_price_visible ?? true) ? 'checked' : '' }}><label class="form-check-label" for="is_price_visible">Show Price</label></div></div></div>
  <h5>Item Details</h5>
  <div class="row"><div class="col-md-4 mb-3"><label class="form-label">Ingredients</label><textarea name="ingredients" rows="2" class="form-control">{{ old('ingredients', $item->ingredients) }}</textarea></div><div class="col-md-4 mb-3"><label class="form-label">Size Label</label><input name="size_label" value="{{ old('size_label', $item->size_label) }}" class="form-control"></div><div class="col-md-4 mb-3"><label class="form-label">Details JSON</label><textarea name="details" rows="2" class="form-control @error('details') is-invalid @enderror">{{ $detailsValue }}</textarea>@error('details')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
  <h5>Restrictions / Visibility</h5>
  <div class="row"><div class="col-md-2 mb-3"><label class="form-label">Minimum Age</label><input type="number" name="minimum_age" min="0" max="99" value="{{ old('minimum_age', $item->minimum_age) }}" class="form-control @error('minimum_age') is-invalid @enderror">@error('minimum_age')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-2 mb-3"><label class="form-label">Sort Order</label><input type="number" name="sort_order" min="0" value="{{ old('sort_order', $item->sort_order ?? 0) }}" class="form-control"></div><div class="col-md-8 mb-3 d-flex flex-wrap gap-4 align-items-end"><div class="form-check form-switch"><input type="hidden" name="is_age_restricted" value="0"><input class="form-check-input" type="checkbox" name="is_age_restricted" value="1" id="is_age_restricted" {{ old('is_age_restricted', $item->is_age_restricted) ? 'checked' : '' }}><label class="form-check-label" for="is_age_restricted">Age Restricted</label></div><div class="form-check form-switch"><input type="hidden" name="is_featured" value="0"><input class="form-check-input" type="checkbox" name="is_featured" value="1" id="is_featured" {{ old('is_featured', $item->is_featured) ? 'checked' : '' }}><label class="form-check-label" for="is_featured">Featured</label></div><div class="form-check form-switch"><input type="hidden" name="is_available" value="0"><input class="form-check-input" type="checkbox" name="is_available" value="1" id="is_available" {{ old('is_available', $item->is_available ?? true) ? 'checked' : '' }}><label class="form-check-label" for="is_available">Available</label></div><div class="form-check form-switch"><input type="hidden" name="is_active" value="0"><input class="form-check-input" type="checkbox" name="is_active" value="1" id="is_active" {{ old('is_active', $item->is_active ?? true) ? 'checked' : '' }}><label class="form-check-label" for="is_active">Active</label></div></div></div>
  <h5>Media</h5>
  @include('admin.components.media-picker', ['model' => $item, 'collection' => 'primary_image', 'label' => 'Primary Image', 'fieldName' => 'primary_image_media_id', 'altFieldName' => 'primary_image_alt_override'])
  @include('admin.components.media-gallery-picker', ['model' => $item, 'collection' => 'gallery', 'label' => 'Gallery', 'fieldName' => 'gallery_media_ids'])
  @include('admin.partials.seo-fields', ['model' => $item, 'mediaModel' => $item, 'mediaCollections' => ['meta_image']])
</div>
<div class="card-footer d-flex gap-2"><button class="btn btn-primary">Save Item</button><a href="{{ route('admin.catalog.items.index') }}" class="btn btn-secondary">Cancel</a></div>
