@extends('admin.layouts.app')
@section('title', 'Media Library')
@section('content')
<main class="app-main"><div class="app-content-header"><div class="container-fluid"><div class="row"><div class="col-sm-6"><h3 class="mb-0">Media Library</h3></div><div class="col-sm-6"><ol class="breadcrumb float-sm-end"><li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li><li class="breadcrumb-item active">Media Library</li></ol></div></div></div></div>
<div class="app-content"><div class="container-fluid">@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif
<div class="card mb-4"><div class="card-header d-flex align-items-center"><h3 class="card-title mb-0">Library</h3><a href="{{ route('admin.media.create') }}" class="btn btn-primary btn-sm ms-auto"><i class="bi bi-upload"></i> Upload Media</a></div><div class="card-body">
<form class="row g-2 mb-3" method="GET"><div class="col-md-4"><input name="search" value="{{ $filters['search'] ?? '' }}" class="form-control" placeholder="Search media"></div><div class="col-md-2"><select name="type" class="form-select"><option value="">All types</option><option value="image" @selected(($filters['type'] ?? '') === 'image')>Images</option></select></div><div class="col-md-2"><select name="status" class="form-select"><option value="">All statuses</option><option value="active" @selected(($filters['status'] ?? '') === 'active')>Active</option><option value="inactive" @selected(($filters['status'] ?? '') === 'inactive')>Inactive</option></select></div><div class="col-md-2"><select name="sort" class="form-select"><option value="">Newest</option><option value="oldest" @selected(($filters['sort'] ?? '') === 'oldest')>Oldest</option></select></div><div class="col-md-2"><button class="btn btn-secondary w-100">Filter</button></div></form>
<div class="row g-3">@forelse($mediaAssets as $media)<div class="col-sm-6 col-lg-3"><div class="card h-100"><img src="{{ $media->getVariantUrl('thumbnail') }}" class="card-img-top" style="height:150px;object-fit:cover" alt="" loading="lazy"><div class="card-body"><h6 class="card-title text-truncate">{{ $media->title ?: $media->original_name }}</h6><p class="small text-secondary mb-1">{{ $media->width }}x{{ $media->height }} | {{ $media->extension }} | {{ $media->human_file_size }}</p><p class="small text-secondary mb-1">Used: {{ $media->attachments_count }}</p><span class="badge {{ $media->is_active ? 'text-bg-success' : 'text-bg-secondary' }}">{{ $media->is_active ? 'Active' : 'Inactive' }}</span></div><div class="card-footer d-flex gap-1"><a href="{{ route('admin.media.show', $media) }}" class="btn btn-info btn-sm">View</a><a href="{{ route('admin.media.edit', $media) }}" class="btn btn-warning btn-sm">Edit</a><form action="{{ route('admin.media.destroy', $media) }}" method="POST" onsubmit="return confirm('Delete this media asset? Physical files will be kept for safety.')" class="ms-auto">@csrf @method('DELETE')<button class="btn btn-danger btn-sm"><i class="bi bi-trash"></i></button></form></div></div></div>@empty<div class="col-12"><p class="text-center text-secondary">No media found.</p></div>@endforelse</div>
<div class="mt-3">{{ $mediaAssets->links() }}</div></div></div></div></div></main>
@endsection
