<div class="card-body">
  <div class="row">
    <div class="col-md-3 mb-3"><label class="form-label">Source <span class="text-danger">*</span></label><select name="source" class="form-select">@foreach($sources as $source)<option value="{{ $source }}" @selected(old('source', $review->source) === $source)>{{ ucfirst($source) }}</option>@endforeach</select>@error('source')<div class="text-danger small">{{ $message }}</div>@enderror</div>
    <div class="col-md-3 mb-3"><label class="form-label">External ID</label><input name="external_id" value="{{ old('external_id', $review->external_id) }}" class="form-control @error('external_id') is-invalid @enderror">@error('external_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-3 mb-3"><label class="form-label">Author Name <span class="text-danger">*</span></label><input name="author_name" value="{{ old('author_name', $review->author_name) }}" class="form-control @error('author_name') is-invalid @enderror" required>@error('author_name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-3 mb-3"><label class="form-label">Rating</label><input type="number" step="0.1" min="1" max="5" name="rating" value="{{ old('rating', $review->rating) }}" class="form-control @error('rating') is-invalid @enderror">@error('rating')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
  </div>
  <div class="row">
    <div class="col-md-4 mb-3"><label class="form-label">Author URL</label><input name="author_url" value="{{ old('author_url', $review->author_url) }}" class="form-control @error('author_url') is-invalid @enderror">@error('author_url')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4 mb-3"><label class="form-label">Review URL</label><input name="review_url" value="{{ old('review_url', $review->review_url) }}" class="form-control @error('review_url') is-invalid @enderror">@error('review_url')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4 mb-3"><label class="form-label">Review Date</label><input type="datetime-local" name="reviewed_at" value="{{ old('reviewed_at', $review->reviewed_at?->format('Y-m-d\TH:i')) }}" class="form-control @error('reviewed_at') is-invalid @enderror">@error('reviewed_at')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
  </div>
  <div class="mb-3"><label class="form-label">Review Text</label><textarea name="review_text" rows="4" class="form-control">{{ old('review_text', $review->review_text) }}</textarea></div>
  <div class="row"><div class="col-md-4 mb-3"><label class="form-label">Sort Order</label><input type="number" name="sort_order" min="0" value="{{ old('sort_order', $review->sort_order ?? 0) }}" class="form-control"></div><div class="col-md-8 mb-3 d-flex gap-4 align-items-end"><div class="form-check form-switch mb-2"><input type="hidden" name="is_featured" value="0"><input class="form-check-input" type="checkbox" name="is_featured" value="1" id="is_featured" {{ old('is_featured', $review->is_featured) ? 'checked' : '' }}><label class="form-check-label" for="is_featured">Featured</label></div><div class="form-check form-switch mb-2"><input type="hidden" name="is_active" value="0"><input class="form-check-input" type="checkbox" name="is_active" value="1" id="is_active" {{ old('is_active', $review->is_active ?? true) ? 'checked' : '' }}><label class="form-check-label" for="is_active">Active</label></div></div></div>
  @include('admin.components.media-picker', ['model' => $review, 'collection' => 'avatar', 'label' => 'Author Avatar', 'fieldName' => 'avatar_media_id', 'altFieldName' => 'avatar_alt_override'])
  @error('avatar_media_id')<div class="text-danger small mb-3">{{ $message }}</div>@enderror
  @include('admin.partials.seo-fields', ['model' => $review, 'mediaModel' => $review, 'mediaCollections' => ['meta_image']])
</div>
<div class="card-footer d-flex gap-2"><button class="btn btn-primary">Save Review</button><a href="{{ route('admin.reviews.index') }}" class="btn btn-secondary">Cancel</a></div>
