@extends('admin.layouts.app')
@section('title', 'Catalog Items')
@section('content')
<main class="app-main"><div class="app-content-header"><div class="container-fluid"><div class="row"><div class="col-sm-6"><h3 class="mb-0">Catalog Items</h3></div><div class="col-sm-6"><ol class="breadcrumb float-sm-end"><li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li><li class="breadcrumb-item active">Catalog Items</li></ol></div></div></div></div>
<div class="app-content"><div class="container-fluid">@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="card mb-4"><div class="card-header d-flex align-items-center"><h3 class="card-title mb-0">Items</h3><a href="{{ route('admin.catalog.items.create') }}" class="btn btn-primary btn-sm ms-auto"><i class="bi bi-plus-lg"></i> Add Item</a></div><div class="card-body">
<form method="GET" class="row g-2 mb-3"><div class="col-md-3"><input name="search" value="{{ $filters['search'] ?? '' }}" class="form-control" placeholder="Search items"></div><div class="col-md-2"><select name="category_id" class="form-select"><option value="">All categories</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(($filters['category_id'] ?? '') == $category->id)>{{ $category->name }}</option>@endforeach</select></div><div class="col-md-2"><select name="business_area" class="form-select"><option value="">All areas</option>@foreach($businessAreas as $area)<option value="{{ $area }}" @selected(($filters['business_area'] ?? '') === $area)>{{ str_replace('_', ' ', ucfirst($area)) }}</option>@endforeach</select></div><div class="col-md-2"><select name="item_type" class="form-select"><option value="">All types</option>@foreach($itemTypes as $type)<option value="{{ $type }}" @selected(($filters['item_type'] ?? '') === $type)>{{ str_replace('_', ' ', ucfirst($type)) }}</option>@endforeach</select></div><div class="col-md-2"><select name="status" class="form-select"><option value="">Any status</option><option value="active" @selected(($filters['status'] ?? '') === 'active')>Active</option><option value="inactive" @selected(($filters['status'] ?? '') === 'inactive')>Inactive</option></select></div><div class="col-md-1"><button class="btn btn-secondary w-100">Go</button></div></form>
<div class="table-responsive"><table class="table table-bordered table-striped align-middle"><thead><tr><th>ID</th><th>Image</th><th>Name</th><th>Category</th><th>Area</th><th>Type</th><th>Price</th><th>Featured</th><th>Available</th><th>Status</th><th>Updated</th><th style="width:190px">Actions</th></tr></thead><tbody>@forelse($items as $item)<tr><td>{{ $item->id }}</td><td>@if($url=$item->getMediaUrl('primary_image', $item->category?->getMediaUrl('image', null, 'thumbnail'), 'thumbnail'))<img src="{{ $url }}" style="width:56px;height:42px;object-fit:cover" alt="">@else - @endif</td><td>{{ $item->name }}</td><td>{{ $item->category?->name }}</td><td>{{ str_replace('_', ' ', ucfirst($item->category?->business_area ?? '')) }}</td><td>{{ str_replace('_', ' ', ucfirst($item->item_type)) }}</td><td>{{ $item->is_price_visible ? ($item->price_label ?: ($item->price ? '$'.$item->price : '-')) : 'Hidden' }}</td><td>{{ $item->is_featured ? 'Yes' : 'No' }}</td><td>{{ $item->is_available ? 'Yes' : 'No' }}</td><td><span class="badge {{ $item->is_active ? 'text-bg-success' : 'text-bg-secondary' }}">{{ $item->is_active ? 'Active' : 'Inactive' }}</span></td><td>{{ $item->updated_at->format('M d, Y') }}</td><td><a href="{{ route('admin.catalog.items.variants.index', $item) }}" class="btn btn-info btn-sm">Variants</a> <a href="{{ route('admin.catalog.items.edit', $item) }}" class="btn btn-warning btn-sm"><i class="bi bi-pencil-square"></i></a> <form action="{{ route('admin.catalog.items.destroy', $item) }}" method="POST" class="d-inline" onsubmit="return confirm('Delete this catalog item?')">@csrf @method('DELETE')<button class="btn btn-danger btn-sm"><i class="bi bi-trash"></i></button></form></td></tr>@empty<tr><td colspan="12" class="text-center text-secondary">No catalog items found.</td></tr>@endforelse</tbody></table></div>{{ $items->links() }}</div></div></div></div></main>
@endsection
