@php $selectedPages = old('pages', $faq->relationLoaded('pages') ? $faq->pages->pluck('id')->all() : []); @endphp
<div class="card-body">
  <div class="row">
    <div class="col-md-4 mb-3"><label class="form-label">Category</label><select name="faq_category_id" class="form-select"><option value="">Uncategorized</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('faq_category_id', $faq->faq_category_id) == $category->id)>{{ $category->name }}</option>@endforeach</select>@error('faq_category_id')<div class="text-danger small">{{ $message }}</div>@enderror</div>
    <div class="col-md-4 mb-3"><label class="form-label">Sort Order</label><input type="number" name="sort_order" min="0" value="{{ old('sort_order', $faq->sort_order ?? 0) }}" class="form-control"></div>
    <div class="col-md-4 mb-3 d-flex gap-4 align-items-end"><div class="form-check form-switch mb-2"><input type="hidden" name="is_featured" value="0"><input class="form-check-input" type="checkbox" name="is_featured" value="1" id="is_featured" {{ old('is_featured', $faq->is_featured) ? 'checked' : '' }}><label class="form-check-label" for="is_featured">Featured</label></div><div class="form-check form-switch mb-2"><input type="hidden" name="is_active" value="0"><input class="form-check-input" type="checkbox" name="is_active" value="1" id="is_active" {{ old('is_active', $faq->is_active ?? true) ? 'checked' : '' }}><label class="form-check-label" for="is_active">Active</label></div></div>
  </div>
  <div class="mb-3"><label class="form-label">Question <span class="text-danger">*</span></label><input name="question" value="{{ old('question', $faq->question) }}" class="form-control @error('question') is-invalid @enderror" required>@error('question')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
  <div class="mb-3"><label class="form-label">Answer <span class="text-danger">*</span></label><textarea name="answer" rows="5" class="form-control @error('answer') is-invalid @enderror" required>{{ old('answer', $faq->answer) }}</textarea>@error('answer')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
  <div class="mb-3"><label class="form-label">Assign Pages</label><select name="pages[]" class="form-select" multiple size="6">@foreach($pages as $page)<option value="{{ $page->id }}" @selected(in_array($page->id, $selectedPages))>{{ $page->name }} ({{ $page->slug }})</option>@endforeach</select>@error('pages')<div class="text-danger small">{{ $message }}</div>@enderror @error('pages.*')<div class="text-danger small">{{ $message }}</div>@enderror</div>
  @include('admin.partials.seo-fields', ['model' => $faq])
</div>
<div class="card-footer d-flex gap-2"><button class="btn btn-primary">Save FAQ</button><a href="{{ route('admin.faq.questions.index') }}" class="btn btn-secondary">Cancel</a></div>
