@extends('admin.layouts.app')
@section('title', 'SEO Settings')
@section('content')
<main class="app-main"><div class="app-content-header"><div class="container-fluid"><div class="row"><div class="col-sm-6"><h3 class="mb-0">SEO Settings</h3></div><div class="col-sm-6"><ol class="breadcrumb float-sm-end"><li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li><li class="breadcrumb-item active">SEO Settings</li></ol></div></div></div></div>
<div class="app-content"><div class="container-fluid">@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<form method="POST" action="{{ route('admin.seo.settings.update') }}" class="card">@csrf @method('PUT')
<div class="card-body">
  <h5>General</h5>
  <div class="row"><div class="col-md-4 mb-3"><label class="form-label">Site Name</label><input name="site_name" value="{{ old('site_name', $seoSetting->site_name) }}" class="form-control"></div><div class="col-md-4 mb-3"><label class="form-label">Default Title</label><input name="default_title" value="{{ old('default_title', $seoSetting->default_title) }}" class="form-control"></div><div class="col-md-4 mb-3"><label class="form-label">Title Separator</label><input name="title_separator" value="{{ old('title_separator', $seoSetting->title_separator ?: '|') }}" class="form-control"></div></div>
  <div class="row"><div class="col-md-6 mb-3"><label class="form-label">Default Description</label><textarea name="default_description" rows="3" class="form-control">{{ old('default_description', $seoSetting->default_description) }}</textarea></div><div class="col-md-6 mb-3"><label class="form-label">Default Keywords</label><textarea name="default_keywords" rows="3" class="form-control">{{ old('default_keywords', $seoSetting->default_keywords) }}</textarea></div></div>
  <div class="row"><div class="col-md-4 mb-3"><label class="form-label">Author</label><input name="default_author" value="{{ old('default_author', $seoSetting->default_author) }}" class="form-control"></div><div class="col-md-4 mb-3"><label class="form-label">Publisher</label><input name="default_publisher" value="{{ old('default_publisher', $seoSetting->default_publisher) }}" class="form-control"></div><div class="col-md-4 mb-3"><label class="form-label">Copyright</label><input name="default_copyright" value="{{ old('default_copyright', $seoSetting->default_copyright) }}" class="form-control"></div></div>
  <div class="mb-3"><label class="form-label">Default Meta Image URL</label><input name="default_meta_image" value="{{ old('default_meta_image', $seoSetting->default_meta_image) }}" class="form-control"></div>
  @include('admin.components.media-picker', ['model' => $seoSetting, 'collection' => 'default_meta_image', 'label' => 'Default Meta Image Media Library', 'fieldName' => 'default_meta_image_media_id', 'altFieldName' => 'default_meta_image_alt_override'])
  <hr><h5>Canonical / Robots</h5>
  <div class="row"><div class="col-md-6 mb-3"><label class="form-label">Canonical Base URL</label><input name="canonical_base_url" value="{{ old('canonical_base_url', $seoSetting->canonical_base_url) }}" class="form-control @error('canonical_base_url') is-invalid @enderror">@error('canonical_base_url')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-3 mb-3"><div class="form-check form-switch mt-4"><input type="hidden" name="default_robots_index" value="0"><input class="form-check-input" type="checkbox" name="default_robots_index" value="1" id="default_robots_index" {{ old('default_robots_index', $seoSetting->default_robots_index) ? 'checked' : '' }}><label class="form-check-label" for="default_robots_index">Default Robots Index</label></div></div><div class="col-md-3 mb-3"><div class="form-check form-switch mt-4"><input type="hidden" name="default_robots_follow" value="0"><input class="form-check-input" type="checkbox" name="default_robots_follow" value="1" id="default_robots_follow" {{ old('default_robots_follow', $seoSetting->default_robots_follow) ? 'checked' : '' }}><label class="form-check-label" for="default_robots_follow">Default Robots Follow</label></div></div></div>
  <hr><h5>Social</h5>
  <div class="row"><div class="col-md-4 mb-3"><label class="form-label">Twitter Card</label><input name="twitter_card" value="{{ old('twitter_card', $seoSetting->twitter_card ?: 'summary_large_image') }}" class="form-control"></div><div class="col-md-4 mb-3"><label class="form-label">Twitter Site</label><input name="twitter_site" value="{{ old('twitter_site', $seoSetting->twitter_site) }}" class="form-control"></div><div class="col-md-4 mb-3"><label class="form-label">Facebook App ID</label><input name="facebook_app_id" value="{{ old('facebook_app_id', $seoSetting->facebook_app_id) }}" class="form-control"></div></div>
  <hr><h5>Verification</h5>
  <div class="row"><div class="col-md-6 mb-3"><label class="form-label">Google Site Verification</label><input name="google_site_verification" value="{{ old('google_site_verification', $seoSetting->google_site_verification) }}" class="form-control"></div><div class="col-md-6 mb-3"><label class="form-label">Bing Site Verification</label><input name="bing_site_verification" value="{{ old('bing_site_verification', $seoSetting->bing_site_verification) }}" class="form-control"></div></div>
  <hr><h5>Sitemap / Structured Data</h5>
  <div class="row"><div class="col-md-4"><div class="form-check form-switch mb-3"><input type="hidden" name="sitemap_enabled" value="0"><input class="form-check-input" type="checkbox" name="sitemap_enabled" value="1" id="sitemap_enabled" {{ old('sitemap_enabled', $seoSetting->sitemap_enabled) ? 'checked' : '' }}><label class="form-check-label" for="sitemap_enabled">Sitemap Enabled</label></div></div><div class="col-md-4"><div class="form-check form-switch mb-3"><input type="hidden" name="robots_enabled" value="0"><input class="form-check-input" type="checkbox" name="robots_enabled" value="1" id="robots_enabled" {{ old('robots_enabled', $seoSetting->robots_enabled) ? 'checked' : '' }}><label class="form-check-label" for="robots_enabled">Robots Enabled</label></div></div><div class="col-md-4"><div class="form-check form-switch mb-3"><input type="hidden" name="structured_data_enabled" value="0"><input class="form-check-input" type="checkbox" name="structured_data_enabled" value="1" id="structured_data_enabled" {{ old('structured_data_enabled', $seoSetting->structured_data_enabled) ? 'checked' : '' }}><label class="form-check-label" for="structured_data_enabled">Structured Data Enabled</label></div></div></div>
  <hr><h5>Robots Advanced</h5>
  <div class="mb-3"><label class="form-label">Extra Robots.txt Rules</label><textarea name="robots_txt_extra" rows="5" class="form-control">{{ old('robots_txt_extra', $seoSetting->robots_txt_extra) }}</textarea></div>
</div>
<div class="card-footer"><button class="btn btn-primary">Save SEO Settings</button></div>
</form></div></div></main>
@endsection
